"""Domain-specific prompt bundles."""

from .finance import (
    FINANCE_COVARIATE_DESCRIPTION,
    FINANCE_COVARIATE_PROMPT,
    FINANCE_COMMUNITY_GRAPH_PROMPT,
    FINANCE_COMMUNITY_TEXT_PROMPT,
)

__all__ = [
    "FINANCE_COVARIATE_DESCRIPTION",
    "FINANCE_COVARIATE_PROMPT",
    "FINANCE_COMMUNITY_GRAPH_PROMPT",
    "FINANCE_COMMUNITY_TEXT_PROMPT",
]
